__version__ = '0.8.0'
__name__ = 'airtable-python-wrapper'
__description__ = 'Python API Wrapper for the Airtable API'
__url__ = 'https://github.com/gtalarico/airtable-python-wrapper'
__author__ = 'Gui Talarico'
__license__ = 'The MIT License (MIT)'
__copyright__ = 'Copyright 2017 Gui Talarico'
