__version__ = "0.0.1"
__name__ = "pyairtable"
__description__ = "Airtable API Client in Python"
__url__ = "https://github.com/gtalarico/airtable-python-wrapper"
__author__ = "Gui Talarico"
__authoremail__ = "gtalarico.dev@gmail.com"
__license__ = "The MIT License (MIT)"
__copyright__ = "Copyright 2021 Gui Talarico"
