__version__ = "0.15.3"
__name__ = "airtable-python-wrapper"
__description__ = "Python API Wrapper for the Airtable API"
__url__ = "https://github.com/gtalarico/airtable-python-wrapper"
__author__ = "Gui Talarico"
__authoremail__ = "gtalarico.dev@gmail.com"
__license__ = "The MIT License (MIT)"
__copyright__ = "Copyright 2020 Gui Talarico"
