#!/bin/bash

source ./scripts/console.sh

info 'Pre-Commit Hook'

info "Checking for breakpoints"

breakpoint=$(git grep breakpoint -- '*.py')
if [ -n "$breakpoint" ]
then
    error "COMMIT REJECTED: Please remove breakpoint before commiting."
    error $breakpoint
    exit 1
fi

set -e

make lint
make docs
