#!/bin/bash

echo "> Checking for breakpoints"

breakpoint=$(git grep breakpoint -- '*.py')
if [ -n "$breakpoint" ]
then
    echo "COMMIT REJECTED: Please remove breakpoint before commiting."
    echo $breakpoint
    exit 1
fi

set -e

echo "> Linting"
make lint
